//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTacVienClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLCongTacVienEntities : DbContext
    {
        public QLCongTacVienEntities()
            : base("name=QLCongTacVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tblAboutSite> tblAboutSites { get; set; }
        public DbSet<tblAccount> tblAccounts { get; set; }
        public DbSet<tblContactSite> tblContactSites { get; set; }
        public DbSet<tblInfoSite> tblInfoSites { get; set; }
        public DbSet<tblKhachHang> tblKhachHangs { get; set; }
        public DbSet<tblLichSu> tblLichSus { get; set; }
        public DbSet<tblNhom> tblNhoms { get; set; }
        public DbSet<tblOrder> tblOrders { get; set; }
        public DbSet<tblOrder_Account> tblOrder_Account { get; set; }
        public DbSet<tblPhongBan> tblPhongBans { get; set; }
        public DbSet<tblProduct> tblProducts { get; set; }
        public DbSet<tblSite> tblSites { get; set; }
        public DbSet<tblSite_Product> tblSite_Product { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
    }
}
