//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTacVienClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public tblAccount()
        {
            this.tblAccount1 = new HashSet<tblAccount>();
            this.tblOrder_Account = new HashSet<tblOrder_Account>();
            this.tblOrders = new HashSet<tblOrder>();
            this.tblSites = new HashSet<tblSite>();
            this.tblNhoms = new HashSet<tblNhom>();
            this.tblUsers = new HashSet<tblUser>();
            this.tblPhongBans = new HashSet<tblPhongBan>();
        }
    
        public long MaAccount { get; set; }
        public string TenAccount { get; set; }
        public string LoaiAccount { get; set; }
        public string GhiChu { get; set; }
        public Nullable<long> AccountManager { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayUpdate { get; set; }
        public string UserTao { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<tblAccount> tblAccount1 { get; set; }
        public virtual tblAccount tblAccount2 { get; set; }
        public virtual ICollection<tblOrder_Account> tblOrder_Account { get; set; }
        public virtual ICollection<tblOrder> tblOrders { get; set; }
        public virtual ICollection<tblSite> tblSites { get; set; }
        public virtual ICollection<tblNhom> tblNhoms { get; set; }
        public virtual ICollection<tblUser> tblUsers { get; set; }
        public virtual ICollection<tblPhongBan> tblPhongBans { get; set; }
    }
}
