//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTacVienClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroup_Perrmision
    {
        public int GroupID { get; set; }
        public int PermissionID { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual tblGroupPermission tblGroupPermission { get; set; }
        public virtual tblPermission tblPermission { get; set; }
    }
}
