//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTacVienClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroupPermission
    {
        public tblGroupPermission()
        {
            this.tblUsers = new HashSet<tblUser>();
            this.tblPermissions = new HashSet<tblPermission>();
        }
    
        public int GroupID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayUpdate { get; set; }
    
        public virtual ICollection<tblUser> tblUsers { get; set; }
        public virtual ICollection<tblPermission> tblPermissions { get; set; }
    }
}
