//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTacVienClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSite_Product
    {
        public int SiteID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblSite tblSite { get; set; }
    }
}
