//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTacVienClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSite
    {
        public tblSite()
        {
            this.tblContactSites = new HashSet<tblContactSite>();
            this.tblInfoSites = new HashSet<tblInfoSite>();
            this.tblSite_Product = new HashSet<tblSite_Product>();
        }
    
        public int SiteID { get; set; }
        public string SiteName { get; set; }
        public string Title { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayUpdate { get; set; }
        public Nullable<long> AccountID { get; set; }
    
        public virtual tblAboutSite tblAboutSite { get; set; }
        public virtual tblAccount tblAccount { get; set; }
        public virtual ICollection<tblContactSite> tblContactSites { get; set; }
        public virtual ICollection<tblInfoSite> tblInfoSites { get; set; }
        public virtual ICollection<tblSite_Product> tblSite_Product { get; set; }
    }
}
